#!/bin/bash
set -u -e -C
shopt -s failglob

read -r modeHead modeIndex modeWorktree hashHead hashIndex path <<< "$@"

# Skip symlinks
if test "${modeIndex}" = 120000; then exit 0; fi

# Skip binary files.  Note: Use staged attributes.
mapfile -t -d '' arr < <(git check-attr -z --cached text -- "${path}")
if test "${arr[2]}" = unset; then exit 0; fi

# Get last character.  If it was a newline, make it an x, otherwise
# make sure it is not an x.
lastChar="$(git cat-file blob "${hashIndex}" | tail -c1 | tr $'\nx' xy)"

# newline is not required on empty files
test "${lastChar}" = x -o -z "${lastChar}"
